name: NPCMerchant
main: com.binaryelysium.NPCMerchant.NPCMerchant
version: 0.1
commands:
  merchant:
    description: Control NPC Merchants
    usage: /merchant create <npc name> OR /merchant move <npc name> OR /merchant remove <npc name>