name: NPCTrader
main: com.binaryelysium.NPCTrader.NPCTrader
version: 0.1
commands:
  merchant:
    description: Control NPC Merchants
    usage: /merchant create <npc name> OR /merchant move <npc name>