name: NPCMerchant
main: com.binaryelysium.NPCMerchant.NPCMerchant
version: 0.1
commands:
  merchant:
    description: Control NPC Merchants
    usage: /merchant create npc_name OR /merchant move npc_name OR /merchant remove npc_name  (npc_name is case sensitive)