name: NPCMerchant
main: com.binaryelysium.NPCMerchant.NPCMerchant
version: 0.1
commands:
  merchant:
    description: Control NPC Merchants
    usage: /merchant [create|move|remove] npc_name OR /merchant [yell|broadcast] npc_name message (npc_name is case sensitive)